---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull
  namespace: capoaberto-staging
spec:
  encryptedData:
    .dockerconfigjson: AgDBv2OY5N86BAEiYYmMLy5cVzOJsls1zX//Y9GvfCVef8Yt+j8iv/WWqrdOchURc5wlV1asPTA9zkklr3kqf7eiNtjmn3XVT/EuGbJ1UQEzV/1h6VrDgT4LhJ8L7YAstlO2Cuk4m7qLotH3qpf5uO7L37WSMiOfcsoKzWMHLXqsJiIL+V16LuDQnQO+pih/6B7uioovxkjuRHK2CdqpTl1G/17T0Tn/BgiwZPpZ21CI85RI6Xyc/8iN4EgsZIuEa7NSC79dYPgDImskGNVDXITY874uiwOV6MzcrpFoApcw8YuXDMGEJ/WPyknJ8yK9nd9vsJRwEkM9mGsVRHCxPIKckMO2A4fEKxNEZb49WHFuMqSGiHcL2FNxNGOnAM+dnTEWhc33USi4XFNgHhx4XXaTXGBrCMVT0BhGPrUoeDZzL/6lvGshIGio3p32Bp7agXvUsWhU4/xdkO2PvD1L21V32yonw1GuSd7otWMV/X/bTRMViIycGh0yaoaXbiXSvyTpM9aAZs83TM8ncCQbHZ5zyvLY5E/2DGLDTOuFYI1F0Q8WZbwsmiCFuXQ9AflOJPO9LI875p27OY5jZimu4h+kMh/MQEpz09qDTCuTq3coZ1mXzDmTmsNUBZ6LuinWjuSjyJrFnBspG59WA84fH5e/cAkAstMwnkt3FtyF9ZAgdrUrqjCh7bxHN7aAK66bm/UxZ52bw6kWP1uD7s3S11ykJ0q2K84ba3J/VeDMRuvaUsT/VbyeXwnffoPUSBAIUWs839/XjDf6KcyHqB06WWnfcnnoSIpHKiovCI+43jqgwdrUgLqbN9Gn2YHqrJAmvLkc8SC/QjlWqsuYRTRzZh7jzI6immgvRQ7Jr919Q4l37ziLxHfKdVsZ58Gu3LaY/H+trglmLX+mvQjQzyqN4EyvE44pP9NS1BQoekDfSwPx8ENIrg==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull
      namespace: capoaberto-staging
    type: kubernetes.io/dockerconfigjson
