---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: capoaberto-db
  namespace: capoaberto-staging
spec:
  encryptedData:
    DATABASE_URL: AgCIvXOo5FwiIw3PNC0wQeeUeNm8N2g/HSmeVbVhZYhBYfHb3PcSuhYdWiwJjb6F+vhmHUaKko5JdwORGZo27rMAj/qy6/G2M6XWYUYekVluDRrEA0O5AL8KjHV4j2r+Tbi/iHvnOVANv9y/x4njPD+X5b6Tm6TUIg811grxbng5Q+zTpVZJdmT6Ond5mLidkVl5+ctK064amdipdlBM532QuBs4GT4DMpN2ynwhux+be8mb3XRa+abeBSjs6S4T/CwVFtkO12LOZHfSucWs2prnVFpxicULstruJw4aeEqbvXOeif9mW3XOJ9iPmefnUk5Y5ULq5IPA+GH3gvOkw54eIRu92dJ651fw+cesA18DuzgSBFayqYSR59/lPLRhKNvTfz6xCmy5MPfgfrNwZDEo+0SrkxHxobE9XFTbMtWgsWPd88OcICr+bTJCyAb4o17Bm97xzWcPTUCf653SyVlMx5ts4GcLSm9/DbdTK6/h+4cq5orJKgcCzRI2GVYnoo8lZWqaiCi9D6727kV14XKQIatTjSDrhYum2YwTRj7m5onicYVAT4yLt6sQQs11b6SSMbtCoN9dXwBWyEsfsG8tcOGJVRZeH20QYOxpzosp49z8/5AwMzwRZn0U6MLxC3uLb/JiAY0MBwSkzO8UWjI/iyCKcD5X+sIeWiUuOlCrJrUf1aWQiVworV0ThA0ykys5/org+phnL+cjSV0pRhvl5T2OZkaFg9KEZDNHMmxuJO8Ad1SLyx5Ix53hKiTv7jBNVUP4J1yrGlRoOKhnZo1w+f1I8qZ1PB8j9SCe+BKLM0KlOsSD6fftXI02ikfm13fDbUqUuJiCSGQWf3fCTaWB9m41dStYzZb5Jtt/ST7n
  template:
    metadata:
      creationTimestamp: null
      name: capoaberto-db
      namespace: capoaberto-staging
