---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull
  namespace: originlabs-landing
spec:
  encryptedData:
    .dockerconfigjson: AgBy0uzpdUreFdnL8ACw/wUdEyyRQJnSzUaykFpV017kAa0QQvezQ8RdLGD3A242Kh/epABchf0nPtdsj339yBnl9WSmlnKA12cedkBSN9YqzI5Fv3Urld4XfwHid6R4IHNsXNlljXiDQ3fK6XCZM2b9+QQzUGAZ0B/KnPHcDZy6S2uuCI0b1/9YnwUv5IZwWAx+IY5+AZST0W7ZoIc4QtoZlmJidYoCb2qBHoMdOEb5aP5MKCxQatL8/5IGBj+ukhgOswisNKViFnrv+scuA7so0KSaoE0REDUhOGVpeDNjf5nDmZSbGKnCEwJNu/lokNY47vD9Rjd7Dg79rwvysLFdee+aMWAg4NZEkc5PnM43sOabQy52BxrtLIDnhJozyHZOH9qKD+LMjoPGvc7V6qjxIL/ArU/q1d0il8xrV3PMSswNPFutXleLqKypX3Q6G2LMtnv3k+wlESYHMIay9J7AzwJGkHddOAcd1l8+hkwEsPhvaTTAGAp3kg4i+ZWSweFDbkQ3gtvTGJHMdP11tMso5hDT8mGthxxWqJy1AqNa6O/leAOybKSKjvhJ+1VuI9WqPjbcK7ndYmexn6PQQ6fdj9gRt3eGdmzeRujp02ve4Vq8ENb4zK2WPnEyI6AHNudI9/6I54RVZSofu+ICoxNDdqrnaVzO0POaqH/ylWp+O1uZ+V7bIW/aWItuWh2GLCvj0yCOWW7XWVhhEYpEY4HSZv8ONeIvMveNdPvZ1CF1CtLDnycZqi6SEARVM+LEzi5JOGMoP6J+f4YdGPSHXXrVQS0pmHNzeVFrNVkHtpyOTgH3N8GC5lMEskl6bRT0PXeG2NM0sZqFrCYpvBGb9hiHOub9vbYPcgWKtoREEuCqsyugyZc2PJG7NvrB5XLH4KooLPbfm0EFtWsVsk2f98wKlcfp/Uf0djQMdclTnYkaJHgR
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull
      namespace: originlabs-landing
    type: kubernetes.io/dockerconfigjson
