---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mixtape-secrets
  namespace: mixtape
spec:
  encryptedData:
    password-hash: AgCX2GBbuPL6g53lgACQlLi9/5JD3af4Hq4oOGzBP5ibxZE7heQdKLFk6B3wL/IPU7J7h1dSasgxsnFbYofMJ4yqecqQTroNXGOm4YQiEhri/AlxYct1K2kBAzfkl3u9hqjyejoz88I10WZzvNNd13fdmDVeCyZXZIRgkuGwx+hsF+nNvpd+hU5ri3vNZbru9z/Ov/0kDRgRI43bCAxjo3ksiMOjGHMjXjwYkmYAma7qdjFfm8zj1Oh8m3FqFpH915hH9OcRWBHrjrOGeyWLF+NIjhR2kwXc5y13IslMvHdpAZfyOMRkMD9l3vhbBwcJtn9jK9rwuL2TVH/ovV80Joge4Ma+TL5sU47XYNZi59eXb2ByX9CO8aAWRSHg+XUNaFWjzMQZJsX5CmKaQU75Ss0HPQLeMnDW3GSwD0BYNy+P+3IZmCqp9dkAkaB4yLcx+FpfOiC04soCg0Z+82C/ol56v2X3A4ANqwF81y9nbcMJtaVjfVjwLjDYshEUdgZdZBcNdfR4DT1BYds3IqgHLuXaxe1p+1RJuLDc7vHUZltDmiDROsYfB8M66tYSbjFj066XriBpqln871tdO3BZgS4RnEwOyX0p3SntvVIgzqOqQ7brwx1LfcWSD6tl70G978xwG9uDc0FyfoYow3kRpG/X52eicXj6T1uHt/SNK3L3IEDDThjvvckkNbYz1Pam9J6d773/5cpYuMFHrL73zdbm0+LAaHlqMQ7JwbcjmEGL1ExeQCE9yyLuAHDJO8Ohe5vHqOzbjiQbna0sM48=
    session-secret: AgAJq4EpjEBnHHaPZD6rmS1O25i9Ww213U16cWbjEDVYRfNl/tjAkzzSkl4MxzPvSrXsHjLeYwEWcMMqrEMB/U2r+Gm88NiAoFYyCpY9Wb6JoREAUtNdomM8XlWJEOEsJm7/QZelYBDY1Jud246stcgwfOOAV00mHcacGRpy9VM6fYw+0/zEx+pjEjARGWxlyLNOM2kzjA1ssvC1rd0z+6POBQ2ZGLVpplY51pXlNzaAvkOnoU00CwfYkp3qgXcilFZ0hD0JJ8amDb1TK4+arFa+yqrjnuy2zHOLy3UnAJWG8Qox/vWyFY3r/gBbCIBQqknphYZiGOEjNfmwwqb92NeROreMik0woeYlWbJ5d/GIHuSbm3aiK2peDMtErSAtQmVWm+hTsHTqBH5hal3lVfjCbL64XQU6xLmSizSqI6NAVnh0NRJfb7G+qkoXxqojt+b1/CEtkd9ljvIsW/LXOa4Fzvyx5NtpqN0SgjwoZDqS/Ty9nRh0OErMK/klrCiwWX44BIYkNFjWCaOk2hu7ph8KvuGxTBWApQu3OG0mAHQshTNlIITzdyAYRtqLgR1B4/jiLyVXfh/iHlfwz0wq/FIjxGL/waVxn5iHyCxxf4N53KDq1XTH6EUIKJMf/Hd6lgHMMhv4/CmMdIHU7FSdtMCdIkhNsIkgtfQTuW0fwbpcnNHNW88HX3h6rLCPlu9ExAB9P+V7iIne5O2XajL8lBhHVshHDNCMTV9jpOZr3c3Fz3UvifBho1+1ErzAcwqlnoRs5sNgQkCdm/5Q0yC6cBuy
  template:
    metadata:
      creationTimestamp: null
      name: mixtape-secrets
      namespace: mixtape
