---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDRMugqv03rGew1jrRH3K1gXteQA+iMlcswiw0TOuscx6LjDkrxVqpgbzNOUOSPcTP7yot0DFt4R0tfDZ5TZPZdugmTeptVZKL3JLs4jq0oqhz79qfYN88bNblOCdtEDnAXW4efvYrNbAzhR4DShWwlcvdEBaWz/K677Gnb5GYA3PWh+kthdHD0tIeiDyAXZpIhdfx1ts+rW0YeWdnE9VQHuZpaqTBMrEUtgntl3qX9olWJHxYx/Hq9g0CUvruJTMgwCqXTAgr7I29l2vx8VsO7JBHXFuf5eLpYxglkAEfk323ASi0ADzgKARbO/taSjffZ5DuWlJnD6KC1S3nmZmcPHoHmuSFkVStuIFh8nQ6e+NN3SJj+nuai1GQBvxj6hN8foEdAqkJp2PvR/rF/PUWnyJ4OvRjLjl7SpzBmPolut6jMDWZ6ZZsqqSfQJkeTjBjNv1gbouYUqSM+8L33kcxUwXNvR7Ra5Pz6KW7Lw1SwyrTpUgNG/PDb+I9TDVnIxb//e5N2fe6ZiIGkyHIDYbWOOiCybtzNfJX+zUrRUhLldsYDAzyxNLphsu8EVswOHjbpi95ALOR3CUAQxwv6EaNq+jyqpj6kgGekSlNhXS6EEtT8ij02LLBnl3ixTaNxosZC7gJVGy1QBC2bSLBQyyRQcIM/dj7hJYSlJQZmunLfRSQaH/hQDwWL9R+7MBAqRsC/28M6Vne7ifZZeV1IvBnr7Im90d7SiJI7CmZjnp3a8A==
    admin-user: AgDEJkQPsTez9xnvss9F5MyLOd+eVq9qcq2AkM6cbMWRL0j0jycpOPamtX34oLYAjhHTKdwP6qsKtNRzgIT8/XSOPqS9gLqb1w7C2U8zuPuWdsKIfv01oSLR9Hxo/GEINotR2v1D3aS4x8ZQM2w0yKE7oiHLuWZk0DXmBlQeMmlVIYm4yIPviTy3PhMmyPaBX5wYRrE89ycLCOU0JYQIm+JeZloOE1sb0NmXbkU3jN7AWSUaYV+neW3PpaFq9VhxQ6p8mpuyw/QX4fkSM219Pvv5AFVCOt7rKgFUsOsOCtXg1MDOCeAbYASqLMDot9qEAfwra8/5Ao//wkGwYwKSQm7fSVL9jC19wxcSRQoJR+gX5YzxB2BOivyybgkPB/GjcVHC4dFY+ekqPUMHiPru7aUoPJoE5eapDGkzrOKDNFZoCwPGLTrZ9M5qwwCxqYK5MaCp/FmQKcb4WcukhyHnvc8JKmTRJQs7tgjdPZx8PFq9Wi5EXF1sZycQnP3FIuwzqRHIMiPoL8lBx2i1mUt1lem2BF42tvLYInHPKAgdQh3Qmi8SnJ4A8PnoX87oS22lsVsDuWUfs4cUorZRU5bQS5hbVxYCgch/hKcNbXOCiDdg3jcZtPXXRCQETDOlzeRenuWFaxzb6Ic+lO9QuEoVUdlrJftS/HmQVByAe0BfQEttAPYjQwq62MVDl3cKImwJoxTV5jX2Zw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: Opaque
