apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sotto
  namespace: sotto
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: sotto.lab.mateuseap.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sotto
                port: { number: 80 }
  tls:
    - hosts: [sotto.lab.mateuseap.com]
      secretName: sotto-tls
