---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sotto-secrets
  namespace: sotto
spec:
  encryptedData:
    deepgram-api-key: AgB/5Gcjj3n89T4BbuoOBFAPxggBGcPsgYzhKQD15cr2gp08toAPfOlU9GMwuWmEuYt6FhisrmJ7xapXOeigvmIECagwaAo72Jh7n1TR28lOusrEGdMKoDRT5sCuqTbJjx2GFWs23uHUcURHVgs0RkMhihhWPkayVLfuQhhPXtSTHTqLM0SKikzAZiKd0lPTV1ZB6ZDy6xfqgyHwiHGQOLDNzwqUmwo/9Cp1DNAzSLxhgDLQq/qMFXxcFTIab/OAYNbFn8+KbggyBrE8qkZCyPJNuk6DQC4Vq7ewgd0dcU8QOUNTUA9so11andg15wwZNweTPnmziDT19V17rKneo51FKuQfeRmffrXiB3aB6Fv98h9LvJFsROXyt6bNQQ58BxyAYw7idAxvREh7l+EnPtfc+YRkS3joALTWIoEmrKGv7cVsb8ZV9XUpoeShTrIXU4wWIBLlRsgTZEgP0Ut063vp3dHGS/DgRW5AfTl17hJ7mw7/Cv8wDtiIrM6kQtToJ/Gx86yZDZ0r4sveiiHOulDjaAsytTcKimycPDGWvr5isqr2mmiD3Ls08R7OY+/u7zS9/zuqFF+Chw7mDaGhHDL3ibOJfYf1FD+ukiEaiifnRXjf++BfYH+JlFt629m/PXwIJmxIVObe21f0A75STNUG4UAvky/XrYzbUV72B7DUbTxrjVJ/9PX1zeW9PemMRoROfz4sQOojh31jeEe8v7yMGUaXRq5bzgcP5+OSl6nRnHE5HQmKEm8/
    login-password-hash: AgBXvs4waMH+2T+pEvutiYrFCGGNfPCScssYmhuB9Rv8QfEMotNJT+hGkixhuJnuZaSLt4oBXMhJTpbQHrq5pZy89PRoGFwsRzX4XVgvIxBzElJ/QgyXZ/EuRlq8xFDNU8mjAmcSwFDQF78aAvGxp8CUO8RVa7j9y4C1y7/MnKqvdDG4PlKV8k1tggmOSMyCCaDpVmWr6WrWj11N4C9eXwCfFm+sm84YmHV1TtYYsh1uRFCxXWzckwoMlqRBI7J2m0tgG91DmhszTjrdBfjCHuDZZ+UG30ZTWZyimNuInmgq6C56CV2FFs3Mvk9mWnzJhNjtmehPjROnruiFQi9Yjj0MkumNwdwpv2rwhLAqgyOwOX40EFp0+uVi+KQOvv1pQnHKzwP6C0Yqz8G9uhMJlQN51DFrhvsgzHcNHZoBn99gTJgfRbQgeSqGzQoH3UjEys9CS1pdhwANOkndmfn4OrqfCjzSycvNEy+PQLk09DBetsU9+X01iQe4fAUvrqy1YAMl/JUUDj1K5tLBZI0RQvT4vfDa2OLCntfBxQFH06qqFNi92I/hRsO87ao2Zm+FPmSK/oSpX0mRSvV3lpL7pCuyYcocCTuc7Dvh+0DwhCSGssMplhGU1JHEDSAoam0ijkgLVeFJFmBVszrJ+0dFvCW45vRSoYALfcmXULGzBCvjyZD3XsSn1WPLTq765CLFOSIt4B39guq8a8crZlJUc9uNKJ6cWdRMaWi9DuSfP8QGtT7WjcBzHRrzKWC0BaEKZtnfU6sp26BXvUlcynA=
  template:
    metadata:
      creationTimestamp: null
      name: sotto-secrets
      namespace: sotto
    type: Opaque