---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sotto-secrets
  namespace: sotto
spec:
  encryptedData:
    deepgram-api-key: AgBzsSTlcHZi7t9U1k5Oq7uNshshF+5u3KQNhdLssY+OBOSOraOuhebeuG9x22fji/FRKnIlDt+m7f3TC594Vg00FGZyqsfLwhdjraCUsSKhMe38LeObDqkWWSDjM5b+gOLQMaZ6GLvOy/7tLrnCIHkm/IJZcWb7FybylJHYg41ilLyFgTA9Wq6J5tq7/EJjMB2ESoLDc6fwXq7AQmc46lPZxdZ85oQh/oCncukt34l04KitwADBulY3HtFGZkyLNXDb2Vd3LcgtDhuswG9faEo+IN4JP0V+Zt+j7P+JPEr1W97KuZ0Dz7HTY7VXGg8raj+iC243rxMinvAN2Ez6aUre1yG3LqqIssIG7N3tVHHJzawxv/3Ck9AzFVQz7KhHtltyKvNerZ/LvYIFKknz/sjngt8q1ClcVWtnlRnWdPv4Lr35GAnWjNVzfW+LxA2fazyv2sUEhviPG/iZ340jSCmSczM7X3SLfGIsuk/zRtACjwa1zYDtk0JR/kvSNNs27hKyg7NTKHSLL72mP7IGB9mpZeI+5mIVNV5aRHvHUhAb5NN5Y4YQ/5DjvK1FmC7HsPr0/swCcRVZOmzxRlm/OAr4g4NLUeY+ntXqwW4L8mbNWnRcsmzR6j5FbyeC9t1WRdBsx1MgCksoznngpi3lYZRR8123rWXVinMYIWKSdEcERxTaQjFDJEDHVitj9eHi/gjVgQBb4QimrwTrmV30WZuGtNcf3FHSZaf4yiiL8s67nPI=
    session-token: AgDM9drhvDLxmMbi3+eKiUOe763UaWYzTzokk7bRE+3r1qpvNy8bgbKQsM29xqiXNRCmpFrzxNLI2CB86vhy9bI07CHYeprFDPipd4YrF7VPDtv0uZw393LsrDtN3YKjcG4q6IAwaPDfqbtljRtJkOD9eyhtnbyhnzbIvi5ilKkyPnP5WdFf7An2yrW0jVYtxR+tsqQsrYaGldfmv3lYJhDrhqYSiLFUXi7CoWd6nS9LIZtcLLntIXLQh9l1x4+39nAri8KtkHaxJ3Ldn6EkA7ESxRUCuIancoG2V5w/AVMlKhxLikYcPv8VxE0aHxL6qm119NUcYUHKYiJ6ITptud5twr018mSBhHkr44G41EIfACy0BEBeDshil6s6L8/1EHNaxMwV5OHItd+joKVYUZeF0ste0tba/X+97z4cx86VC+ZBeE6kgjlNmAlhWTzFThpE7YP+TGDDTbHVBQu2YiG31QIG+Ru5VG14pgIQYgbDikKEegjQpLpgv0/+4eLihzmU+3/6bv1g8P8evnYE6tReBoX1s/hUNoSeyB8kVofRwBv8C4Mj7sjaiWoil8xTMC0HfYDC1OvR6ofB0jZo21NXG/c/XZ8gzLfLS30aC5eD9YUSqoDQHNYls5a1nbv27+/+X/xE5hXDyKWXvZqAsSaI4OgZl3W2+tNt+mavhCLjk3eDk8nPPpLJr6obRojV4Rs6vcl98fFtqcVUSZK22UYbghMNbSomUnUe3tvv3Qm1qswq9ro6A9Yoz7k4hC9gkHs+VHNldCzKbmqYb/4AG2wQ
  template:
    metadata:
      creationTimestamp: null
      name: sotto-secrets
      namespace: sotto
    type: Opaque
