---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sotto-secrets
  namespace: sotto
spec:
  encryptedData:
    deepgram-api-key: AgCBoKMOoy03xT2BHTkr0s2Q+MEgmcL/BFS/aEqv+IqlvwVZVO2yNZcfgZG8V5SIwcShOIsX5Ooa5gn37wwYvD+d1v0h/mY5m/6WQeOaXJJ6xrdjfTtczvIUvOrzw187No9gRamnb0AfZAldBYDGLy3GZ05w2rhkwm7HDIBqWOgCyZJfRpeBk8M3fAqgi6ZywzCh0BYmxfktlRZRd8Wi32nuUO85o/PpuiUJcc/2GBaDQhsDXyOKStgtKoY0fn7Apq64usi4hsGcm9N8zgUHNssFl7DtYycHuvIfuXErPlBJtiwVrP6o2zzYvbfCxVrGKYVtsiVBtNhYaW7RGW5vXbBrshfQje0u/U9UjrZqUTakRtWItNzgEBbAHmEyy8wMpr1soJtZ5AwQGPZkI2L0P0hr+pIuC7STQgBv8dQIMxkBEuGtsDwqQKVi6da1X0PIjavieJJoyN1iaZCPS6jAEDVvQztj3JqsmaOXk7ci6DyU3sypwBcNtEuv3O8kEGRqbJ+2p0b1RXCwWKvKQsysJmiWBvpBh8NZLxpEUrYIIkElpwu6lyVXxAcGCsC57+bOj3YWpEvvWwh3fctDeHDlZb/+TjYn9n7+vjcQrDRJoi8ojK8UAKzdQmfz783nlk5YO0MJEpn3dVOnhR9S+/knYsJvECRWw5ba0al/HV1m6k4cPORd6iv2S3lAn92mtpFulTCXRSaOYMv01LLUy7hZRS9ib4NFUXERXNuE8lbLeBFmj4s=
    session-token: AgCZB/lGh+ndCWENCJv5lEaoROXlpXRdQYMkufeZBBWJJ0KHKpc4S0HR2QpKiUG644igDFS//M0GOLlPWj8KjOztJRwLUDL+NQdSfZry8YVEFUUEuBOdylYCnfgEIwYaIZlSq9Z4oSV9S398y+UsFQ7oJQQMnIpSc1hJ8TTo4K1ubrp4GyDMNsyoRBI1+0eDGMOiL90lGkknpHphgai6plARFvKIb3GFoynkAAJm2n6MIhSuIXor8OYKcCKBvd15XW69mLEfzcYGhFL9H/Od5KafHsHQssqle5dFKuk6gHmL9DPEgU7NNjmtLbKO68OJuNLRm98zeHcEeoyLwf9QupB7FlncjRZDJunIk9LDAidMPNbhqDRrWqX8elYMN3rQLvTycxdjiYWTy2ARlA5ujGFwkuYt0ftcVh9o5kJe4+MINvGctR3LDppAxmamdmx5Nr00nXaFxykUhhxR1xiR+k9lNINU89jrum3T5oXjHrNRU3lyWfe8mR0TUi83e+PUESTYtBCRnfxh1xK65sO0jR3zQA8Mr9fsCEa6IZQNxqk70nUmSoBD/IGp+ihdSID4QeY3qfUNr487SCENGpLlvLwh91WFbpjkDr9JE79F5p7SbDUj0tSKm6V80VESgv4SmEKG3Be/yVxeNdqBQrDSyn8M5/XL8ilGQrjlXlsOTvKHlUieh3PLr5xca8pW9Z95nm2v4mrdEqrQKkSHTcFNBnYrDMsE+IKFG/NGtv2ovb2R8ti55SajjHzk4h1n
  template:
    metadata:
      creationTimestamp: null
      name: sotto-secrets
      namespace: sotto
    type: Opaque
