---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull
  namespace: sotto
spec:
  encryptedData:
    .dockerconfigjson: AgAfhNR+mYpS86BoqvI3lkHs2yH8GfKl17f/rh1gRz7SbWpOUF7ik5TnK+hIJOVy72x7g0PDiMy0P84GkNIkJbY6IQQov3JkADNThtgZmsnwc2eBzmjqTnZs4HRG/Cq0jkWc81GyGcemA1FMXWdZinzd4XjPHgK5O3d7Qf1peI0r39ZSmsMT9IAXln4Z7ABF0fHHAqdNVi6rGPIKqigP5ms/7txy2XiHTwtlvI458NbxPf0jUOGjGpfh/WW6ucR2d9DgAoJTW5jCrXdH7gMV7NQD1NGakxTHI3xaA0QknHxuA/ImNm+3VlffHQP6nwYQ+vvCY5wMFF4r9krI5/9ZdL6QwX31pQG+lDavoIhMsIIP0iwMa4CrDACbILTYoqJkSs6Li38+P1vMoRlnT8W9u5DyiLe0ANxzY01oNqdLjNSLAhcSE9DcvifkreEsHjzMZwAogtlbW3mkbk8Fh2SI0fYok8PbPmGs20UP/kie91RjnfE3xDVw7VmetnyfYPliuA6xPg3g6n/W0JwFZSHt8G+bUW1U6iNNEke5kOv8pVFB1qRDKtVqUPmzf63gGeTG+F97Q92lbXY9p0XwmA8lhvfmHRWNI0kPECC+vv5HMSkjddqxVAW0nndoQ/BkMQFJtm/0kAvuFIFWj9C9Ixc/ZKAxwf/XE0JI594++h72hvoNxzjtAEoy3c7JtagoNKAHam/6IKOM2fI162O0+dkmlg3KzANu1K/CdZF3ekuwU1K+aHGOYt+igTzdoPpuhQxa7yaDvpGnXlypo1amT/nLVqSh/zIqWgWFjLjA76mr4f4zpjQYDVHiYG84matDD49ciCbXU3V3+g==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull
      namespace: sotto
    type: kubernetes.io/dockerconfigjson
